name: "🚀 Feature Request"
description: "Propose a new feature or improvement."
title: "[FEATURE] "
labels: ["type:feature", "status:discussion"]
body:
  - type: markdown
    attributes:
      value: |
        *Propose features for @PO and @PM review.*
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered.
  - type: textarea
    id: impact
    attributes:
      label: Expected Impact
      description: How will this improve the project?
